name: Phvdl
on:
  workflow_dispatch:
  schedule:
    - cron:  '30 6 * * *'
jobs:
  run-sync-service:
    runs-on: ubuntu-latest
    steps:
      - name: Pyrogram
        run: |
          pip install pyrogram 
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: Cd Into Repo
        run: |
          cd ${{ github.workspace }}
      - name: Yt-dlp
        run: |
           sudo wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp & sudo chmod a+rx yt-dlp
      - name: Running the Script 
        run: |
          python main.py
