name: Phvdl
on:
  workflow_dispatch:
  schedule:
    - cron:  '30 6 * * *'
jobs:
  run-sync-service:
    runs-on: ubuntu-latest
    steps:
      - name: Downloading the Script
        run: |
          wget https://gist.github.com/BlackFoxy616/224aa1ec41f88c581ff9ed3f2de10011/raw/phvdl.sh
      - name: Permission
        run: |
           chmod 777 phvdl.sh
      - name: Running the Script
        run: |
           ./phvdl.sh
      - name: Ls
        run: |
           ls MainDrive
